MovieManager/Areas/Content/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MMApi.DataAccess;
using MMApi.Helpers;
using MMApi.Internal.DataAccess;
using MMApi.Models;
using MovieManager.Areas.Content.Models;
using MovieManager.Areas.Content.ViewModels;

namespace MovieManager.Areas.Content.Controllers
{
    [Area("Content")]
    [Authorize]
    public class ListController : Controller
    {
        private readonly MovieContext _context;
        private readonly IUserLists _userLists;
        private readonly UserListHandler _listHandler;
        private readonly MovieHandler _movieHandler;

        public ListController(MovieContext context, IUserLists userLists)
        {
            _context = context;
            _userLists = userLists;
            _listHandler = new UserListHandler(_context);
            _movieHandler = new MovieHandler(_context);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Create([FromBody] CreateList list)
        {
            var userList = await _listHandler.Create(User.FindFirstValue(ClaimTypes.NameIdentifier), list.Title);

            return Json(userList);
        }

        [HttpDelete]
        public async Task<JsonResult> Delete(int id)
        {
            if (id < 0)
            {
                return Json(-1);
            }

            var deletedListID = await _listHandler.Delete(id, User.FindFirstValue(ClaimTypes.NameIdentifier));

            return Json(deletedListID);
        }

        public async Task<JsonResult> GetLists()
        {
            var userLists = await _listHandler.GetListsForUser(User.FindFirstValue(ClaimTypes.NameIdentifier));
            _userLists.AddItemsToList(userLists);

            return Json(userLists);
        }

        public IActionResult Overview(int id)
        {
            ListOverviewViewModel overviewVM = new ListOverviewViewModel();

            UserList list = _listHandler.GetListOverview(listID: id);

            overviewVM.UserList = list;

            return View(overviewVM);
        }

        [HttpPost]
        public async Task<JsonResult> AddToList([FromBody] AddRemoveList requestDetails)
        {
            return Json(await HandleAddRemoveRequest(requestDetails, "add"));
        }

        public async Task<JsonResult> RemoveFromList([FromBody] AddRemoveList requestDetails)
        {
            return Json(await HandleAddRemoveRequest(requestDetails, "remove"));
        }

        public async Task<IActionResult> RemoveMovieFromList(int listID, string movieTitle, string movieType, bool isDefault)
        {
            AddRemoveList removeReq = new AddRemoveList(listID, movieTitle, movieType, isDefault);
            await HandleAddRemoveRequest(removeReq, "remove");

            return RedirectToAction("Overview", new { id = listID });
        }

        public async Task<int> HandleAddRemoveRequest (AddRemoveList requestDetails, string action)
        {
            try
            {
                if (requestDetails.ListID <= 0 || requestDetails.Title == null || requestDetails.Type == null)
                {
                    throw new ArgumentNullException();
                }

                string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);

                if (action == "remove")
                {
                    await _listHandler.RemoveFromList(requestDetails.ListID, requestDetails.Title, requestDetails.Type);
                }
                else if (requestDetails.IsDefault)
                {
                    await _listHandler.AddToDefaultList(requestDetails.ListID, requestDetails.Title, requestDetails.Type, userID);
                }
                else
                {
                    await _listHandler.AddCustomToList(requestDetails.ListID, requestDetails.Title, requestDetails.Type);
                }

                return requestDetails.ListID;
            }
            catch (Exception)
            {
                return -1;
            }
        }

        [HttpGet]
        public async Task<JsonResult> GetUserLists(string title, string type)
        {
            Movie movie = await _movieHandler.GetExistingLocalMovie(title, type);
            List<UserList> lists = await _listHandler.GetListsForUser(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var listsWithMovieAdded = await _listHandler.GetListsWithMovieAdded(lists, movie);

            return Json(listsWithMovieAdded);
        }
    }
}

MovieManager/Areas/Content/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MMApi.DataAccess;
using MMApi.Internal.DataAccess;
using MovieManager.Areas.Content.Models;
using Newtonsoft.Json;

namespace MovieManager.Areas.Content.Controllers
{
    [Area("Content")]
    [Authorize]
    public class MovieController : Controller
    {
        private readonly MovieContext _context;
        private readonly MovieHandler _movieHandler;

        public MovieController(MovieContext context)
        {
            _context = context;
            _movieHandler = new MovieHandler(_context);
        }

        public async Task<IActionResult> Details(string title, string type)
        {
            ApiMovie movie = new ApiMovie();
            movie =
                JsonConvert.DeserializeObject<ApiMovie>
                (JsonConvert.SerializeObject(await _movieHandler.GetApiMovie(title, type)));

            return View(movie);
        }
    }
}

MovieManager/Areas/Content/Views/List/Index.cshtml
@model UserListsViewModel

@{
    ViewData["Title"] = "Lists";
}


<lists-table />

MovieManager/Areas/Content/Views/List/Overview.cshtml
@model ListOverviewViewModel

@{
    ViewData["Title"] = Model.UserList.Title;
}



<div class="list-overview">
    <h2>@Model.UserList.Title</h2>

    <div class="list-overview-movies">
        @if (Model.UserList.Movies == null || Model.UserList.Movies.Count == 0)
        {
            <p>No movies added yet!</p>
        }
        else
        {
            <table>
                <tr class="list-headers">
                    <th></th>
                    <th>Title</th>
                    <th>Remove</th>
                </tr>

                @foreach (var listMovie in Model.UserList.Movies)
                {
                    <tr class="list-row">
                        <td>
                            <a asp-area="Content"
                               asp-controller="Movie"
                               asp-action="Details"
                               asp-route-title="@listMovie.Movie.Title"
                               asp-route-type="@listMovie.Movie.Type">
                                <img src="@listMovie.Movie.Poster" alt="@listMovie.Movie.Title" class="list-overview-poster" />
                            </a>
                        </td>

                        <td>
                            <a asp-area="Content"
                               asp-controller="Movie"
                               asp-action="Details"
                               asp-route-title="@listMovie.Movie.Title"
                               asp-route-type="@listMovie.Movie.Type">
                                @listMovie.Movie.Title
                            </a>
                        </td>

                        <td>
                            <a asp-area="Content"
                               asp-controller="List"
                               asp-action="RemoveMovieFromList"
                               asp-route-listID="@Model.UserList.UserListID"
                               asp-route-movieTitle="@listMovie.Movie.Title"
                               asp-route-movieType="@listMovie.Movie.Type"
                               asp-route-isDefault="@Model.UserList.IsDefault">
                                Remove
                            </a>
                        </td>
                        
                    </tr>
                }
            </table>
        }
    </div>
</div>



@section Style {
    <style>
        .list-overview {
            margin-top: 5vh;
        }

        .list-overview-movies {
            margin-top: 5vh;
        }

        .list-overview-poster {
            height: 6vh;
        }

        .list-overview table {
            width: 100%;
        }

        .list-headers {
            font-size: 2.2vh;
        }

        .list-headers, .list-row {
            height: 8vh;
        }

        .list-row:nth-child(2n) {
            background-color: rgb(235, 235, 235);
        }

        .list-row td {
            font-size: 1.8vh;
        }

        .list-row td:nth-child(1), .list-headers th:nth-child(1) {
            padding-left: 15px;
            width: 8vh;
        }

        .list-row td:nth-child(2n), .list-headers th:nth-child(2n) {
            min-width: 80%;
        }
    </style>
}