MovieManager/Areas/Content/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MMApi.DataAccess;
using MMApi.Helpers;
using MMApi.Internal.DataAccess;
using MMApi.Models;
using MovieManager.Areas.Content.Models;
using MovieManager.Areas.Content.ViewModels;

namespace MovieManager.Areas.Content.Controllers
{
    [Area("Content")]
    [Authorize]
    public class ListController : Controller
    {
        private readonly MovieContext _context;
        private readonly IUserLists _userLists;
        private readonly UserListHandler _listHandler;
        private readonly MovieHandler _movieHandler;

        public ListController(MovieContext context, IUserLists userLists)
        {
            _context = context;
            _userLists = userLists;
            _listHandler = new UserListHandler(_context);
            _movieHandler = new MovieHandler(_context);
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> Create([FromBody] CreateList list)
        {
            var userList = await _listHandler.Create(User.FindFirstValue(ClaimTypes.NameIdentifier), list.Title);

            return Json(userList);
        }

        [HttpDelete]
        public async Task<JsonResult> Delete(int id)
        {
            if (id < 0)
            {
                return Json(-1);
            }

            var deletedListID = await _listHandler.Delete(id, User.FindFirstValue(ClaimTypes.NameIdentifier));

            return Json(deletedListID);
        }

        public async Task<JsonResult> GetLists()
        {
            var userLists = await _listHandler.GetListsForUser(User.FindFirstValue(ClaimTypes.NameIdentifier));
            _userLists.AddItemsToList(userLists);

            return Json(userLists);
        }

        public IActionResult Overview(int id)
        {
            ListOverviewViewModel overviewVM = new ListOverviewViewModel();

            UserList list = _listHandler.GetListOverview(listID: id);

            overviewVM.UserList = list;

            return View(overviewVM);
        }

        [HttpPost]
        public async Task<JsonResult> AddToList([FromBody] AddRemoveList requestDetails)
        {
            return Json(await HandleAddRemoveRequest(requestDetails, "add"));
        }

        public async Task<JsonResult> RemoveFromList([FromBody] AddRemoveList requestDetails)
        {
            return Json(await HandleAddRemoveRequest(requestDetails, "remove"));
        }

        public async Task<IActionResult> RemoveMovieFromList(int listID, string movieTitle, string movieType, bool isDefault)
        {
            AddRemoveList removeReq = new AddRemoveList(listID, movieTitle, movieType, isDefault);
            await HandleAddRemoveRequest(removeReq, "remove");

            return RedirectToAction("Overview", new { id = listID });
        }

        public async Task<int> HandleAddRemoveRequest (AddRemoveList requestDetails, string action)
        {
            try
            {
                if (requestDetails.ListID <= 0 || requestDetails.Title == null || requestDetails.Type == null)
                {
                    throw new ArgumentNullException();
                }

                string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);

                if (action == "remove")
                {
                    await _listHandler.RemoveFromList(requestDetails.ListID, requestDetails.Title, requestDetails.Type);
                }
                else if (requestDetails.IsDefault)
                {
                    await _listHandler.AddToDefaultList(requestDetails.ListID, requestDetails.Title, requestDetails.Type, userID);
                }
                else
                {
                    await _listHandler.AddCustomToList(requestDetails.ListID, requestDetails.Title, requestDetails.Type);
                }

                return requestDetails.ListID;
            }
            catch (Exception)
            {
                return -1;
            }
        }

        [HttpGet]
        public async Task<JsonResult> GetUserLists(string title, string type)
        {
            Movie movie = await _movieHandler.GetExistingLocalMovie(title, type);
            List<UserList> lists = await _listHandler.GetListsForUser(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var listsWithMovieAdded = await _listHandler.GetListsWithMovieAdded(lists, movie);

            return Json(listsWithMovieAdded);
        }
    }
}

MovieManager/Areas/Content/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MMApi.DataAccess;
using MMApi.Enums;
using MMApi.Internal.DataAccess;
using MMApi.Models;
using MovieManager.Areas.Content.Models;
using MovieManager.Areas.Content.ViewModels;

namespace MovieManager.Areas.Content.Controllers
{
    [Area("Content")]
    [Authorize]
    public class SearchController : Controller
    {
        private readonly int _pageSize = 10;
        private readonly MovieContext _context;
        private readonly IUserLists _userLists;
        public static MovieSearchViewModel searchVM = new MovieSearchViewModel();

        public SearchController(MovieContext context, IUserLists userLists)
        {
            _context = context;
            _userLists = userLists;
        }

        private void ResetViewModel()
        {
            searchVM.ApiMovies = new List<ApiMovieShort>();
            searchVM.Movies = new List<Movie>();
            searchVM.Source = "local";
            searchVM.Title = "";
            searchVM.Type = "any";
            searchVM.Page = 1;
            searchVM.Person = "";
            searchVM.Genre = "";
        }

        private SearchSource PopulateViewModel
            (string title = "",
            string source = "local",
            string genre = "",
            string person = "",
            int page = 1,
            bool isMovie = false,
            bool isSeries = false)
        {
            SearchSource result = SearchSource.local;

            if (source != "" && Enum.TryParse<SearchSource>(source, out SearchSource searchSource))
            {
                result = searchSource;
                searchVM.Source = source;
            }
            else
            {
                ResetViewModel();
            }

            if (title != "")
            {
                searchVM.Title = title;
            }

            if (isMovie)
            {
                searchVM.Type = "movie";
            }

            if (isSeries)
            {
                searchVM.Type = "series";
            }

            if (isMovie && isSeries)
            {
                searchVM.Type = "any";
            }

            if (searchVM.Source != source)
            {
                searchVM.Page = 1;
            }
            else
            {
                searchVM.Page = page;
            }

            if (genre != "")
            {
                searchVM.Genre = genre;
            }

            if (person != "")
            {
                searchVM.Person = person;
            }

            string userID = User.FindFirstValue(ClaimTypes.NameIdentifier);
            searchVM.UserID = userID;
            searchVM.IsMovie = isMovie;
            searchVM.IsSeries = isSeries;

            return result;
        }

        public async Task<IActionResult> Index(string title = "", string type = "", string source = "", string genre = "", string person = "", int page = 1)
        {
            try
            {
                bool isMovie = type == "movie" ? true : type == "any" ? true : false;
                bool isSeries = type == "series" ? true : type == "any" ? true : false;
                SearchSource searchSource = PopulateViewModel(title, source, genre, person, page, isMovie, isSeries);

                if (searchSource == SearchSource.omdb)
                {
                    MovieHandler movieHandler = new MovieHandler(_context);
                    ApiMovies movies = await movieHandler.GetApiMovies(title, type, page);
                    searchVM.ApiMovies = movies.Search;
                }

                var lists = await _context.UserLists.Where(ul => ul.UserID == User.FindFirstValue(ClaimTypes.NameIdentifier)).ToListAsync();
                _userLists.AddItemsToList(lists);

                return View(searchVM);

            }
            catch (Exception)
            { 
                throw;
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index([Bind("Title", "Source", "Person", "Genre", "Page", "IsMovie", "IsSeries")] MovieSearchViewModel data)
        {
            PopulateViewModel(data.Title, data.Source, data.Genre, data.Person, data.Page, data.IsMovie, data.IsSeries);

            return RedirectToAction("Index", new
            {
                title = searchVM.Title,
                type = searchVM.Type,
                source = searchVM.Source,
                person = searchVM.Person,
                genre = searchVM.Genre,
                page = searchVM.Page
            });
        }
    }
}

MovieManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.flatly.light.css" />
    <link href="~/dist/app.css" rel="stylesheet" />
</head>
<body>
    <div class="page-wrap">
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="Content" asp-controller="Home" asp-action="Index">MovieManager</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <partial name="_LoginPartial" />
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Content" asp-controller="Search" asp-action="Index">Search</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Content" asp-controller="List" asp-action="Index">Lists</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container" id="app">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MovieManager
            <br />
            &copy; Movie data provided by the <a href="https://www.omdbapi.com/">OMDb API</a>.
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://kit.fontawesome.com/32e727ba59.js" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/dist/app.js"></script>
    <script>
        new Vue({
            el: '#app'
        });
    </script>

    @RenderSection("Scripts", required: false)
</body>
</html>

@RenderSection("Style", required: false)

<style>
    html, body {
        height: 100%;
    }

    .page-wrap {
        min-height: 100%;
        margin-bottom: -90px;
    }

        .page-wrap:after {
            content: "";
            display: block;
        }

        .footer, .page-wrap:after {
            /* .push must be the same height as footer */
            height: 90px;
        }

    .footer {
        padding: 10px;
    }
</style>

MovieManager/Views/Shared/_LayoutHome.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.flatly.light.css" />
</head>
<body>

    @RenderBody()

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>